import os, sys, re, string
import datetime, subprocess

# Created by: Sam Khalouei
# Purpose: Accepts the "effect-stats.csv" file generated by the snpEff tool to extract the number of "Downstream", "Inergenic",
#   "Upstream", "Exonic", and "Intronic" variants

File_prefix = sys.argv [ 1 ]
Sample = sys.argv [ 2 ]
Batch = sys.argv [ 3 ]

inputFile=File_prefix+".Exclude3orMoreOf19Controls.0000.concat.effects-stats.csv"
outputFile=File_prefix+".Exclude3orMoreOf19Controls.0000.concat.effects-stats-numbers.txt"

myInput=open(inputFile,"r")
myOutput=open(outputFile,"w")

myList = myInput.readlines()

Downstream_num=0
Intergenic_num=0
Upstream_num=0
Exon_num=0
Intron_num=0

for myLine in myList:
	if " , " in myLine:
		spline=myLine.split(" , ")
		if spline[0] == 'DOWNSTREAM':
			Downstream_num = int(spline[1])	
		elif spline[0] == 'INTERGENIC':
			Intergenic_num = int(spline[1])	
		elif spline[0] == 'UPSTREAM':
			Upstream_num = int(spline[1])	
		elif spline[0] == 'EXON':
			Exon_num = spline[1]	
		elif spline[0] == 'INTRON':
			Intron_num = spline[1]	

	else:
		continue

total_intergenic = str(Downstream_num + Intergenic_num + Upstream_num)

myOutput.write(Sample+","+Batch+","+total_intergenic+","+"INTERGENIC"+"\n")
myOutput.write(Sample+","+Batch+","+Exon_num+","+"EXON"+"\n")
myOutput.write(Sample+","+Batch+","+Intron_num+","+"INTRON"+"\n")

myInput.close()
myOutput.close()
